Temporary dockerfile fix

diff --git a/sdks/aperture-js/Dockerfile b/sdks/aperture-js/Dockerfile
--- a/sdks/aperture-js/Dockerfile
+++ b/sdks/aperture-js/Dockerfile
@@ -15,9 +15,13 @@ RUN npm ci
 # Bundle app source
 COPY . .
 
-RUN npm run build
+RUN npm run pre-build && npm run build && npm run post-build
 
-HEALTHCHECK --interval=5s --timeout=60s --retries=3 --start-period=5s \
-    CMD wget --no-verbose --tries=1 --spider 127.0.0.1:8080/health || exit 1
+# package.json scripts (Need to fix)
+#    "grpc-client": "npm run build && node ./lib/client.js",
+#    "example": "npm run build && node ./lib/example/example.js",
 
-CMD [ "node", "./lib/example/example.js" ]
+# HEALTHCHECK --interval=5s --timeout=60s --retries=3 --start-period=5s \
+#    CMD wget --no-verbose --tries=1 --spider 127.0.0.1:8080/health || exit 1
+
+# CMD [ "node", "./lib/example/example.js" ]
